services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend:z
    working_dir: /app/backend
    entrypoint: ["sleep", "infinity"]
